# Generated by Django 3.0.5 on 2020-05-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_auto_20200519_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='mitigate',
            field=models.TextField(null=True),
        ),
    ]
