# Generated by Django 3.0.5 on 2020-06-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_link_mitigate'),
    ]

    operations = [
        migrations.CreateModel(
            name='word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
