# Generated by Django 3.0.5 on 2020-06-29 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_atlinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='atLinks',
        ),
    ]
